/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'data', 'id', 'readAt', 'title', 'type', 'updatedAt', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare data: any | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PasswordResetSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'updatedAt', 'userId'] as const
  $columns = PasswordResetSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SubscriptionSchema extends BaseModel {
  static $columns = ['canceledAt', 'createdAt', 'creemCustomerId', 'creemProductId', 'creemSubscriptionId', 'currentPeriodEnd', 'currentPeriodStart', 'id', 'plan', 'status', 'updatedAt', 'userId'] as const
  $columns = SubscriptionSchema.$columns
  @column.dateTime()
  declare canceledAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare creemCustomerId: string
  @column()
  declare creemProductId: string
  @column()
  declare creemSubscriptionId: string | null
  @column.dateTime()
  declare currentPeriodEnd: DateTime | null
  @column.dateTime()
  declare currentPeriodStart: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare plan: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['authMethod', 'avatarKey', 'createdAt', 'creemCustomerId', 'email', 'emailMarketing', 'emailProductUpdates', 'emailSecurityAlerts', 'emailVerificationToken', 'emailVerifiedAt', 'emailWeeklyDigest', 'firstName', 'id', 'lastName', 'password', 'pendingEmail', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare authMethod: string
  @column()
  declare avatarKey: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creemCustomerId: string | null
  @column()
  declare email: string
  @column()
  declare emailMarketing: boolean | null
  @column()
  declare emailProductUpdates: boolean | null
  @column()
  declare emailSecurityAlerts: boolean | null
  @column()
  declare emailVerificationToken: string | null
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare emailWeeklyDigest: boolean | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare pendingEmail: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
